# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _spell_checker
else:
    import _spell_checker

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _spell_checker.delete_SwigPyIterator

    def value(self):
        return _spell_checker.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _spell_checker.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _spell_checker.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _spell_checker.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _spell_checker.SwigPyIterator_equal(self, x)

    def copy(self):
        return _spell_checker.SwigPyIterator_copy(self)

    def next(self):
        return _spell_checker.SwigPyIterator_next(self)

    def __next__(self):
        return _spell_checker.SwigPyIterator___next__(self)

    def previous(self):
        return _spell_checker.SwigPyIterator_previous(self)

    def advance(self, n):
        return _spell_checker.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _spell_checker.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _spell_checker.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _spell_checker.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _spell_checker.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _spell_checker.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _spell_checker.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _spell_checker:
_spell_checker.SwigPyIterator_swigregister(SwigPyIterator)
class dictionary_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _spell_checker.dictionary_t_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _spell_checker.dictionary_t___nonzero__(self)

    def __bool__(self):
        return _spell_checker.dictionary_t___bool__(self)

    def __len__(self):
        return _spell_checker.dictionary_t___len__(self)

    def __getslice__(self, i, j):
        return _spell_checker.dictionary_t___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _spell_checker.dictionary_t___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _spell_checker.dictionary_t___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _spell_checker.dictionary_t___delitem__(self, *args)

    def __getitem__(self, *args):
        return _spell_checker.dictionary_t___getitem__(self, *args)

    def __setitem__(self, *args):
        return _spell_checker.dictionary_t___setitem__(self, *args)

    def pop(self):
        return _spell_checker.dictionary_t_pop(self)

    def append(self, x):
        return _spell_checker.dictionary_t_append(self, x)

    def empty(self):
        return _spell_checker.dictionary_t_empty(self)

    def size(self):
        return _spell_checker.dictionary_t_size(self)

    def swap(self, v):
        return _spell_checker.dictionary_t_swap(self, v)

    def begin(self):
        return _spell_checker.dictionary_t_begin(self)

    def end(self):
        return _spell_checker.dictionary_t_end(self)

    def rbegin(self):
        return _spell_checker.dictionary_t_rbegin(self)

    def rend(self):
        return _spell_checker.dictionary_t_rend(self)

    def clear(self):
        return _spell_checker.dictionary_t_clear(self)

    def get_allocator(self):
        return _spell_checker.dictionary_t_get_allocator(self)

    def pop_back(self):
        return _spell_checker.dictionary_t_pop_back(self)

    def erase(self, *args):
        return _spell_checker.dictionary_t_erase(self, *args)

    def __init__(self, *args):
        _spell_checker.dictionary_t_swiginit(self, _spell_checker.new_dictionary_t(*args))

    def push_back(self, x):
        return _spell_checker.dictionary_t_push_back(self, x)

    def front(self):
        return _spell_checker.dictionary_t_front(self)

    def back(self):
        return _spell_checker.dictionary_t_back(self)

    def assign(self, n, x):
        return _spell_checker.dictionary_t_assign(self, n, x)

    def resize(self, *args):
        return _spell_checker.dictionary_t_resize(self, *args)

    def insert(self, *args):
        return _spell_checker.dictionary_t_insert(self, *args)

    def reserve(self, n):
        return _spell_checker.dictionary_t_reserve(self, n)

    def capacity(self):
        return _spell_checker.dictionary_t_capacity(self)
    __swig_destroy__ = _spell_checker.delete_dictionary_t

# Register dictionary_t in _spell_checker:
_spell_checker.dictionary_t_swigregister(dictionary_t)
class correction_node_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    trie_node = property(_spell_checker.correction_node_t_trie_node_get, _spell_checker.correction_node_t_trie_node_set)
    ula_node = property(_spell_checker.correction_node_t_ula_node_get, _spell_checker.correction_node_t_ula_node_set)
    prefix = property(_spell_checker.correction_node_t_prefix_get, _spell_checker.correction_node_t_prefix_set)

    def __init__(self):
        _spell_checker.correction_node_t_swiginit(self, _spell_checker.new_correction_node_t())
    __swig_destroy__ = _spell_checker.delete_correction_node_t

# Register correction_node_t in _spell_checker:
_spell_checker.correction_node_t_swigregister(correction_node_t)
class SpellChecker(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, _dictionary_path, _tolerance):
        _spell_checker.SpellChecker_swiginit(self, _spell_checker.new_SpellChecker(_dictionary_path, _tolerance))

    def check_word(self, query):
        return _spell_checker.SpellChecker_check_word(self, query)

    def correct_word(self, query):
        return _spell_checker.SpellChecker_correct_word(self, query)

    def load_dictionary(self, filename):
        return _spell_checker.SpellChecker_load_dictionary(self, filename)
    __swig_destroy__ = _spell_checker.delete_SpellChecker

# Register SpellChecker in _spell_checker:
_spell_checker.SpellChecker_swigregister(SpellChecker)

